### ISSUE TITLE
[Doc] Contributor Guidlines

### ISSUE THREAD

**Issue by isdanni** [TRI-AMDD/GMP-featurizer#1]
Seems that CONTRIBUTING.md is empty. Here are a few good examples you can refer to:

- [GitHub Contribution Guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md)
- [Open Government Contribution Guidelines](https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md)
- [Requests Contribution Guidelines](https://requests.readthedocs.io/en/latest/dev/contributing/)

This is to meet the following review criteria:

Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by isdanni** [comment]
linking https://github.com/openjournals/joss-reviews/issues/5476 to track review progress

**Comment by RayLei-TRI** [comment]
@isdanni Thank you so much for the suggestion and resources! I have added the file

**Comment by isdanni** [comment]
thanks!
