### ISSUE TITLE
[Paper] Review comments

### ISSUE THREAD

**Issue by bdice** [TRI-AMDD/GMP-featurizer#3]
Hi @RayLei-TRI! I am reviewing the JOSS paper submitted here: https://github.com/openjournals/joss-reviews/issues/5476

I am opening this issue to track my comments on the paper, as I complete the reviewer checklist. I am writing this as a checklist if you'd like to check things off as they are addressed.

> **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] Your repository is Apache 2.0 licensed, but it says it is based on code from https://github.com/ulissigroup/amptorch which is GPL-3.0 licensed. Have you checked whether your code's licensing is correct? I am not a lawyer (nor am I able to audit your software) but in my understanding, GPL software cannot be relicensed under a "permissive" license like Apache 2.0 without the permission of all contributors.

> **Contribution and authorship:** Has the submitting author (@RayLei-TRI) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] I don't see contributions from Joseph Montoya listed in the software or cited theory papers. Has Joseph agreed to be a coauthor? Maybe a small acknowledgement of the coauthors' contributions could be helpful. Sometimes folks use "[CRediT](https://www.elsevier.com/authors/policies-and-guidelines/credit-author-statement)" for a short summary of contributions. See also: https://joss.readthedocs.io/en/latest/submitting.html#authorship I don't have strong feelings, as long as this paper complies with JOSS expectations.

> **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] I see a sentence in the Overview section: "Please refer to section ?? for more details." The reference seems to be broken here.
- [x] "Although this package does not explicitly depend on ASE [...]". I would try to write this more like "Two of the most widely used Python libraries in chemistry and materials science are ASE (cite) and pymatgen (cite). The gmp-featurizer library provides APIs that can read atomic systems as input from these libraries, though they are not required as dependencies."
  - Bonus: You might also mention what that means for users who need to read files with their system geometry. I have used a similar design in another analysis package, where file I/O was not explicitly part of the package but accepting inputs from other libraries (like ASE or pymatgen) allowed the package to leverage _other_ libraries' I/O functionality to get data into a format accepted by the package we wrote. It's a nice benefit of the interoperability!
- [x] Capitalize the language name "Python" unless referring to the executable command `python`.

> **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://pandoc.org/MANUAL.html#extension-citations)?

- [x] Please check the citations are rendering properly. There are at least two I saw, marked "Ray?" and "collins_accelerated_2017", that appear to be incorrect.

> **Installation:** Does installation proceed as outlined in the documentation?
- [x] The command `python install -e .` in the README is incorrect. I think it's meant to say `pip install -e .`.

> **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] I think the README and/or Jupyter Notebooks need to go farther to be useful. I was able to run the notebooks but didn't know what to do with the results. Where do the inputs come from? Is the pseudopotential file a standardized input format? Can you give more information about how that can be generated? Once features are computed, can a simple machine learning model be trained, or can the features be visualized? How are users supposed to make use of the HDF5 files that are produced in the "cache" directory? Can examples of these use cases be presented?

> **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] #6

> **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] #5

> **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
- [x] Deferring to issue #1 for this, since it has been requested already.

**Comment by JosephMontoya-TRI** [comment]
Thanks for the review @bdice, awesome feedback.

Just wanted to drop a note to indicate I have agreed to be a co-author, and believe I fulfill the "active project direction" aspect of this codebase.

**Comment by bdice** [comment]
@JosephMontoya-TRI Awesome, thanks!

**Comment by RayLei-TRI** [comment]
Thanks @bdice  for the detailed comments and suggestions! 
I'm working on the tasks, and will update here

**Comment by RayLei-TRI** [comment]
@bdice Thanks again for the great suggestions and comments!
We have so far addressed most of them (except the documentation and testing workflow, which we are working on now), please see the updated master branch. We will also keep you updated here.

One great point you mentioned is about the examples and what downstream tasks are possible.  We have added a simple example for training a simple ML model to the atomic Mulliken charge with GMP features. This is of course not the only application, some important applications include using it to train machine learning force field (as described in the original GMP paper), or train to other atom-resolved or spatially-resolved properties. However, these researches are still ongoing so we think it's outside the scope of this package for now, but will add them in when appropriate. On the other hand, we give the users the option to cache the computed features in case they need to access them afterward.  For example when the features need to be accessed again in downstream/different applications, or when there is a system crash and features calculated and stored in memory could be lost. It is of course not always needed, just an option.

**Comment by RayLei-TRI** [comment]
@bdice Thanks again for the suggestions!
I think we have completed all the listed tasks, and the repo is definitely better now. 
Please let us know what you think, or if you have any other concerns.

**Comment by bdice** [comment]
Thank you! I will be out for a few days but I can review this again next week. I’ll set a reminder. 👍

**Comment by bdice** [comment]
Thanks for your many improvements to this repository! This is much better than last time I reviewed.

I have a few remaining comments:

1. The README mentions a file `test.cif` in its example snippet, but it's not clear where this file is located or how to acquire it. The README example snippet uses `ase` but doesn't instruct the user to install it, nor is it a dependency of this package.

2. I built the documentation locally. It's rather sparse. Perhaps you can help guide users to the main classes in the API docs by writing some content on the index page. Also I see this warning when building:

```
GMP-featurizer/docs/source/modules.rst: WARNING: document isn't included in any toctree
```

3. I'm not sure how to get the latest paper to render. I commented here about that: https://github.com/openjournals/joss-reviews/issues/5476#issuecomment-1613871776

**Comment by RayLei-TRI** [comment]
Hi @bdice, hope you had a great weekend and sorry about the belated response
we have just updated the code accordingly. an example cif file is added, and we have updated the webpage with some more content. The compiled can be found [here](https://github.com/openjournals/joss-reviews/issues/5476#issuecomment-1615277983)

Thanks again for your comments, and please let us know if you have any further comments!

**Comment by bdice** [comment]
I opened https://github.com/TRI-AMDD/GMP-featurizer/pull/10 with a couple small suggestions, then I'll approve my review. Thanks for the changes you've implemented!
